require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/pay_laters', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # PayLater. As you add validations to PayLater, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      PayLater.create! valid_attributes
      get pay_laters_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      pay_later = PayLater.create! valid_attributes
      get pay_later_url(pay_later)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_pay_later_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'renders a successful response' do
      pay_later = PayLater.create! valid_attributes
      get edit_pay_later_url(pay_later)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new PayLater' do
        expect do
          post pay_laters_url, params: { pay_later: valid_attributes }
        end.to change(PayLater, :count).by(1)
      end

      it 'redirects to the created pay_later' do
        post pay_laters_url, params: { pay_later: valid_attributes }
        expect(response).to redirect_to(pay_later_url(PayLater.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new PayLater' do
        expect do
          post pay_laters_url, params: { pay_later: invalid_attributes }
        end.to change(PayLater, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post pay_laters_url, params: { pay_later: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested pay_later' do
        pay_later = PayLater.create! valid_attributes
        patch pay_later_url(pay_later), params: { pay_later: new_attributes }
        pay_later.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the pay_later' do
        pay_later = PayLater.create! valid_attributes
        patch pay_later_url(pay_later), params: { pay_later: new_attributes }
        pay_later.reload
        expect(response).to redirect_to(pay_later_url(pay_later))
      end
    end

    context 'with invalid parameters' do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        pay_later = PayLater.create! valid_attributes
        patch pay_later_url(pay_later), params: { pay_later: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested pay_later' do
      pay_later = PayLater.create! valid_attributes
      expect do
        delete pay_later_url(pay_later)
      end.to change(PayLater, :count).by(-1)
    end

    it 'redirects to the pay_laters list' do
      pay_later = PayLater.create! valid_attributes
      delete pay_later_url(pay_later)
      expect(response).to redirect_to(pay_laters_url)
    end
  end
end
